### ISSUE TITLE
Stability problems

### ISSUE THREAD

**Issue by AndrewLoeppky** [AndrewLoeppky/ATSC409#2]
Integrating equations 

There are currently 4 deriv functions to feed into the integrator, and the goal is to create a stable function that can solve (1) and (2)  as written in 409_finalproj_equations. The code currently uses deriv_dfsn_only, which solves decoupled equations for  temperature and wind profiles using the explicit DuFort-Frankel scheme. (Effectively a "heated rod" problem and something analogous to 2d poisueille flow respectively). 

The DFF scheme becomes unstable for the modified version to solve the coupled equations. Is there a way to modify the current derivs functions to make them stable? Or should I turn to implicit schemes like Crank-Nicholson?

[heat.pdf](https://github.com/AndrewLoeppky/ATSC409/files/4422513/heat.pdf)

[409_finalproj_equations.pdf](https://github.com/AndrewLoeppky/ATSC409/files/4422478/409_finalproj_equations.pdf)

**Comment by AndrewLoeppky** [comment]
@phaustin

**Comment by phaustin** [comment]
adding @susaneallen -- @AndrewLoeppky have you confirmed that it is stable if you satisfy [7.10](https://github.com/AndrewLoeppky/ATSC409/files/4422513/heat.pdf)?   For reference [here is the current discretization](https://github.com/AndrewLoeppky/ATSC409/blob/715662a452c5d1d10a242dcf22d4084b6f03335c/anabatic_flow_v5.py#L152-L159)

**Comment by AndrewLoeppky** [comment]
FCTS is unstable for every timestep ive tried, even if it satisfies 7.10... Probably a mistake in the function?

edit: yes, there was a mistake in the function, it is stable when 7.10 is satisfied
