### ISSUE TITLE
Very large errors compared with exact soln

### ISSUE THREAD

**Issue by AndrewLoeppky** [AndrewLoeppky/ATSC409#3]
@phaustin 
Ran the simulation for the steady state case with physical inputs taken directly from reference material (requires quite a high resolution and lots of time). I found that the numerical sim has huge errors, as much as 3m/s for the wind speed! From the plot, it appears that it is effectively overestimating the diffusivity K (diffusion const). Is this "numerical diffusion" you spoke of, and could the fix be as simple as adding a tuning parameter p*K to adjust?

referencing anabatic_flow_main.ipynb

**Comment by phaustin** [comment]
would need to see a plot, but that's possible.  The non-pedogogic implementation for this problem is going to be a lot more work.  One approach to characterizing the error would be to nudge the numerical solution to the analytic steady state, and look at how the errors grow following the nudge.

**Comment by AndrewLoeppky** [comment]
Ill commit a new anabatic_flow_main.ipynb in a second here. I read a little bit about numerical diffusion, my current plan is to pick the "effective diffusion constant" by hand to minimize the error. Could also be done iteratively to find the actual minimum, but now I'm mostly geared toward getting the presentation together for monday

edit: new notebook committed

**Comment by AndrewLoeppky** [comment]
@phaustin
Issue resolved, albeit somewhat sloppily. Matched the numerical to analytical by hand by scaling diff constant K. Good enough for now and for mondays presentation.
